variable "hub_public_ip_name" {}
variable "hub_resource_group_location" {}
variable "hub_resource_group_name" {}
variable "hub_public_ip_nic_name" {}
variable "hub_subnet_id" {}
variable "hub_nsg_name" {}
variable "hub_selenium_hub_port" {}
variable "hub_vm_name" {}
variable "hubvmusername" {}
variable "hubvmpassword" {}
